---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: database
    dash.ulagbulag.io/subject: mobilex-exp
spec:
  selector:
    matchLabels:
      app: database
      dash.ulagbulag.io/subject: mobilex-exp
  template:
    metadata:
      labels:
        app: database
        dash.ulagbulag.io/subject: mobilex-exp
    spec:
      containers:
        - name: database
          image: postgres:16
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbpassword
                  key: POSTGRES_PASSWORD
          ports:
            - name: http
              protocol: TCP
              containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: database
    dash.ulagbulag.io/subject: mobilex-exp
spec:
  type: ClusterIP
  selector:
    app: database
  ports:
    - name: http
      protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: dbpassword
stringData:
  POSTGRES_PASSWORD: "xxxx"
